version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: chatwoot:production
    env_file: .env ## Change this file for customized env variables
    volumes:
      - storage:/app/storage
    networks: ['net']

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '${RAILS_PORT}:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
    networks: ['net']

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always
    networks: ['net']

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks: ['net']

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis:/data
    ports:
      - '${REDIS_PORT}:6379'
    networks: ['net'] 

volumes:
  postgres:
  redis:
  storage:

networks:
  net:
    external: true